### ISSUE TITLE
FPM child processes maxed out since v3.3.0 and TYPO3 11LTS + PHP 8.0 + Cloudflare

### ISSUE THREAD

**Issue by DenisMir** [b13/proxycachemanager#21]
We got a weird problem with the extension that leads to maxed out FPM child processes with the latest v3.3.0 version and TYPO3 11LTS (latest patch version) + PHP 8.0 that we can't find the reason for. 

I try do describe what information we collected till now: 

- We had v3.2.0 with TYPO3 10LTS + PHP 7.4 and Cloudflare running for over a year without problems
- After we migrated to TYPO3 11LTS + PHP 8.0 and v3.3.0 of the proxycachemanager the problems began
- The PHP slow log shows hundreds of struggling/hanging requests (a lot of them from the Guzzle underlying Curl (version 7.61.1) called by the proxymanager) 
- The FPM child processes start adding up pretty fast after a restart of the FPM master process
- Removing v3.3.0 immediately stops the problem from happening
- ReInstalling/Requiring the v3.3.0 starts the problem immediately again (child processes add up to the limit till the server gets unreachable from all of the open requests)
- The server environment hasn't changed except the PHP version

In the end this whole behaviour leads to hundreds of health check failures in cloudflare.

@bmack Have you got any idea which could have changed from v3.2.0 to v3.3.0 that could lead to these problems? Unfortunately trying out v3.2.0 is not possible with TYPO3 11LTS + PHP 8.0 due multiple things not being compatible with PHP 8.0. 

Right now I'm out of ideas what the extension could do that leads to these problems since from looking at the code it "just" calls the CF API in the specific provider. 

Perhaps something comes to your mind that I could follow/debug through.

**Comment by DenisMir** [comment]
Hi @bmack, 

One followup here. I found the reason for the load of FPM processes. 

The cloudflare provider does include something that doesn't make sense: 

https://github.com/b13/proxycachemanager/blob/master/Classes/Provider/CloudflareProxyProvider.php#L90

`Flush All Caches` or `Flush Frontend Caches` does lead to reaching the `else` part which purges the whole cache in chunks. For big sites (multiple zones, hundreds of pages, hundreds of image urls) this can add up to thousands of purge requests. 

The fix is simple. Since we want to clear the whole cache (well the interface method says it `flushAllUrls`) it is enough to do the: 

```
            foreach ($this->getZones() as $domain => $zoneId) {
                try {
                    $this->getClient($zoneId)->post('purge_cache', ['json' => ['purge_everything' => true]]);
                } catch (TransferException $e) {
                    $this->logger->error('Could not flush URLs for {zone} via POST "purge_cache"', [
                        'urls' => $urls,
                        'zone' => $zoneId,
                        'exception' => $e,
                    ]);
                }
            }
```

This leads to only <number of zones> requests. 

I will get you a pull request soon.

**Comment by DenisMir** [comment]
Pull request added.

**Comment by DenisMir** [comment]
Ok one more followup on this issue here. The fix above didn't completely solve the issue. I added one more "fix" which drops the images from being added to the cache: https://github.com/Communiacs/proxycachemanager/commit/75ae964ea0f35efa10587e674025d915c77a2c5c

The test is still running in production but for now the problem seems to be gone. 

@bmack Is this asset collector call really that expensive?

**Comment by bmack** [comment]
I think we can drop this in v11.

**Comment by bmack** [comment]
Removed this in v3.4.0 - thanks for the pointer
