### ISSUE TITLE
Caches not cleared on page changes

### ISSUE THREAD

**Issue by SomeBdyElse** [b13/proxycachemanager#5]
Since https://github.com/TYPO3/TYPO3.CMS/commit/b8775ca3458becfe2b31ac214ff9761b1e2e0d85#diff-0df58cdf10f2b3f92e4625bd614e611f was commited to the TYPO3 9 branch, reverse proxy caches do not get cleared anymore if an editor updates the page in the TYPO3 Backend. 

The reason seem to be missing `pageId_` cache tags in the `tx_proxy` cache. 

Before b8775ca the cache tags were added as follows:

```
1) \TYPO3\CMS\Frontend\Http\RequestHandler::handle
calls \TYPO3\CMS\Frontend\Controller\TypoScriptFrontendController::generatePage_preProcessing 
calls \TYPO3\CMS\Frontend\Controller\TypoScriptFrontendController::tempPageCacheContent 
calls \TYPO3\CMS\Frontend\Controller\TypoScriptFrontendController::setPageCacheContent
which adds the pageId_ cache tags to the $tsfe->pageCacheTags

2) \TYPO3\CMS\Frontend\Http\RequestHandler::handle
calls \TYPO3\CMS\Frontend\Controller\TypoScriptFrontendController::generatePage_postProcessing

2.1) calls \B13\Proxycachemanager\Hook\FrontendHook::addCacheableUrlToProxyCache
which reads $tsfe->pageCacheTags and adds them to its own tx_proxy cache. 

2.2) calls 
\TYPO3\CMS\Frontend\Controller\TypoScriptFrontendController::realPageCacheContent
calls \TYPO3\CMS\Frontend\Controller\TypoScriptFrontendController::setPageCacheContent
which adds the pageId_ cache tags to the $tsfe->pageCacheTags again.
```

The call to `\TYPO3\CMS\Frontend\Controller\TypoScriptFrontendController::realPageCacheContent`, which generates the cache tags again, follows _after_ the call to `\B13\Proxycachemanager\Hook\FrontendHook::addCacheableUrlToProxyCache`. 

Place where tx_proxy cache is written:
https://github.com/TYPO3/TYPO3.CMS/blob/5d92c12e99f5d4fb038cfb7079f1daf9056d7785/typo3/sysext/frontend/Classes/Controller/TypoScriptFrontendController.php#L3600

Place where the cache tags will be generated:
https://github.com/TYPO3/TYPO3.CMS/blob/5d92c12e99f5d4fb038cfb7079f1daf9056d7785/typo3/sysext/frontend/Classes/Controller/TypoScriptFrontendController.php#L3622

Since https://github.com/TYPO3/TYPO3.CMS/commit/b8775ca3458becfe2b31ac214ff9761b1e2e0d85#diff-0df58cdf10f2b3f92e4625bd614e611f the call to `\TYPO3\CMS\Frontend\Controller\TypoScriptFrontendController::tempPageCacheContent` is gone, so the `\B13\Proxycachemanager\Hook\FrontendHook::addCacheableUrlToProxyCache` cannot pick up the `pageId_` cache tags anymore. 

Some ideas to fix this: 
A) Move tx_proxy cache write to somewhere in the middleware
B) Move tx_proxy cache write to "hook_eofe"
C) Generate `pageId_` cache tag in `\B13\Proxycachemanager\Hook\FrontendHook::addCacheableUrlToProxyCache`.

With A) and B) I wonder if it is possible to find the cache tags

**Comment by bmack** [comment]
We've just merged a PR which solves this issue by using a proper hook now.

**Comment by bmack** [comment]
Will close this one. I think that 3.4.0 has solved all of this.
